// Local patch (wasm only): Qt's qt_import_qml_plugins() scans the target's own
// QML files via qmlimportscanner; the MuseScoreStudio executable has none, so
// the scanner reports count=0 and none of the MuseScore QML module plugins are
// referenced. In the static wasm build the linker then drops those plugin
// archives and the QML engine cannot resolve any Muse.*/MuseScore.* import
// ("module ... is not installed"). Explicitly importing every plugin class here
// pins their metadata into the executable so the static plugin registry picks
// them up.
//
// The plugin class names come from the <module>_qmlplugin_Muse*Plugin_in.cpp
// files generated by qt_add_qml_module (e.g. Muse_UiPlugin for Muse.Ui).
//
// Part 2 (wasm only): even with every plugin linked, the per-module URI
// registration performed by the file-scope `static const QQmlModuleRegistration`
// objects inside each <module>_qml_qmltyperegistrations.cpp can be garbage
// collected by the wasm linker (their constructors live in .init_array/.data.rel.ro
// that nothing else references; --gc-sections drops them). Without that
// registration the QML engine falls back to reading the module's qmldir, whose
// dependency lines are CMake target names ("import TARGET" / "import muse_ui_qml"),
// which the runtime cannot resolve ("module ... is not installed").
//
// Fix: explicitly call every qml_register_types_<Module>() function up front
// (they are the same functions the dropped QQmlModuleRegistration objects would
// invoke). The symbols are kept alive by QT_KEEP_SYMBOL in the plugin ctor, so
// they are already present in the wasm binary.

#include <QtPlugin>

Q_IMPORT_PLUGIN(Muse_CloudPlugin)
Q_IMPORT_PLUGIN(Muse_DiagnosticsPlugin)
Q_IMPORT_PLUGIN(Muse_ExtensionsPlugin)
Q_IMPORT_PLUGIN(Muse_GraphicalEffectsPlugin)
Q_IMPORT_PLUGIN(Muse_LearnPlugin)
Q_IMPORT_PLUGIN(Muse_MpePlugin)
Q_IMPORT_PLUGIN(Muse_ShortcutsPlugin)
Q_IMPORT_PLUGIN(Muse_ToursPlugin)
Q_IMPORT_PLUGIN(Muse_Ui_DialogsPlugin)
Q_IMPORT_PLUGIN(Muse_UiComponents_LegacyTreeViewPlugin)
Q_IMPORT_PLUGIN(Muse_UiComponentsPlugin)
Q_IMPORT_PLUGIN(Muse_UiPlugin)
Q_IMPORT_PLUGIN(Muse_WorkspacePlugin)
Q_IMPORT_PLUGIN(MuseApi_ControlsPlugin)
Q_IMPORT_PLUGIN(MuseScore_BraillePlugin)
Q_IMPORT_PLUGIN(MuseScore_EngravingPlugin)
Q_IMPORT_PLUGIN(MuseScore_InstrumentsScenePlugin)
Q_IMPORT_PLUGIN(MuseScore_MuseSoundsPlugin)
Q_IMPORT_PLUGIN(MuseScore_NotationScenePlugin)
Q_IMPORT_PLUGIN(MuseScore_PalettePlugin)
Q_IMPORT_PLUGIN(MuseScore_PlaybackPlugin)
Q_IMPORT_PLUGIN(MuseScore_PreferencesPlugin)
Q_IMPORT_PLUGIN(MuseScore_ProjectPlugin)

// --- Part 2: explicit module registration (see header comment) ---

extern void qml_register_types_Muse_Cloud();
extern void qml_register_types_Muse_Diagnostics();
extern void qml_register_types_Muse_Extensions();
extern void qml_register_types_Muse_GraphicalEffects();
extern void qml_register_types_Muse_Learn();
extern void qml_register_types_Muse_Mpe();
extern void qml_register_types_Muse_Shortcuts();
extern void qml_register_types_Muse_Tours();
extern void qml_register_types_Muse_Ui();
extern void qml_register_types_Muse_Ui_Dialogs();
extern void qml_register_types_Muse_UiComponents();
extern void qml_register_types_Muse_UiComponents_LegacyTreeView();
extern void qml_register_types_Muse_Workspace();
extern void qml_register_types_MuseApi_Controls();
extern void qml_register_types_MuseScore_Braille();
extern void qml_register_types_MuseScore_Engraving();
extern void qml_register_types_MuseScore_InstrumentsScene();
extern void qml_register_types_MuseScore_MuseSounds();
extern void qml_register_types_MuseScore_NotationScene();
extern void qml_register_types_MuseScore_Palette();
extern void qml_register_types_MuseScore_Playback();
extern void qml_register_types_MuseScore_Preferences();
extern void qml_register_types_MuseScore_Project();

extern "C" void museRegisterAllQmlModules()
{
    qml_register_types_Muse_Cloud();
    qml_register_types_Muse_Diagnostics();
    qml_register_types_Muse_Extensions();
    qml_register_types_Muse_GraphicalEffects();
    qml_register_types_Muse_Learn();
    qml_register_types_Muse_Mpe();
    qml_register_types_Muse_Shortcuts();
    qml_register_types_Muse_Tours();
    qml_register_types_Muse_Ui();
    qml_register_types_Muse_Ui_Dialogs();
    qml_register_types_Muse_UiComponents();
    qml_register_types_Muse_UiComponents_LegacyTreeView();
    qml_register_types_Muse_Workspace();
    qml_register_types_MuseApi_Controls();
    qml_register_types_MuseScore_Braille();
    qml_register_types_MuseScore_Engraving();
    qml_register_types_MuseScore_InstrumentsScene();
    qml_register_types_MuseScore_MuseSounds();
    qml_register_types_MuseScore_NotationScene();
    qml_register_types_MuseScore_Palette();
    qml_register_types_MuseScore_Playback();
    qml_register_types_MuseScore_Preferences();
    qml_register_types_MuseScore_Project();
}
